In [ ]:
import numpy as np
import jax
jax.config.update("jax_enable_x64", True)
jax.config.update("jax_platform_name", "cpu")
print(jax.devices())
import jaxlib
import jax.numpy as jnp
import flax
import flax.linen as nn
import optax
from typing import Tuple, Callable, Any, Dict, Optional
import numpy.typing as npt
import copy
import pathlib
import matplotlib.pyplot as plt
import time
import json
import ast
import netket as nk
import os
import glob
import sys

sys.path.append("/home/ihuarte/Escritorio/Ivan/NNs")

# os.chdir("/home/ihuarte/Escritorio/Ivan/NN/")

from VA_project.model.model import J1J2Square
from VA_project.engine.runners import Runner

# from NN_utils import load_vstate
# from correlations import correlations_vstate

# from NNs.NN_module.ST_utils import compare_params, masked_optimizer
from frozendict import deepfreeze
from NN_module.ST_utils import print_tree

In [1]:
%run ./VMC_simulation.py

/home/ihuarte/miniconda3/envs/conda_env/lib/python3.12/site-packages/netket/operator/_local_operator/base.py:348: OperatorMultiplicationDeprecationWarning: 
The '*' operator for multiplying operators is deprecated and will be removed in a future version.

Please use the '@' operator instead:
  - Replace: operator1 * operator2
  - With:    operator1 @ operator2

The '@' operator is Python's standard matrix multiplication operator.


-------------------------------------------------------
For more detailed informations, visit the following link:
	 https://netket.readthedocs.io/en/latest/api/_generated/errors/netket.errors.OperatorMultiplicationDeprecationWarning.html
or the list of all common errors and warnings at
	 https://netket.readthedocs.io/en/latest/api/errors.html
-------------------------------------------------------

  warnings.warn(OperatorMultiplicationDeprecationWarning())


Running exact diagonalization...
Energy ED: -8.45792335139484


────────────────────────────────────── 🧲 CM: J1J2Square   🧠 NN: OnlyAnsatz ──────────────────────────────────────

🧱 Size: 4x4

╭────────────────────────────────────────────────── SIMULATION ───────────────────────────────────────────────────╮
│ ╭─────────────── Sampler ───────────────╮  ╭────────────── Schedule ───────────────╮                            │
│ │ rules=             prules= [0.2, 0.7, │  │ learning_rate=            sampler= {} │                            │
│ │ ['LocalRule',      0.1]               │  │ {'epochs_struct':                     │                            │
│ │ 'Exchange',                           │  │ [[[2000]]],                           │                            │
│ │ 'InvertMagnetiza…                     │  │ 'modes_struct': [[[[...               │                            │
│ │ n_ranks= 1         n_chains_per_rank= │  ╰───────────────────────────────────────╯                            │
│ │                    32                 │                                                                       │
│ │ n_samples_per_ch…  chunk_vstate= 512  │                                                                       │
│ │ 64                                    │                                                                       │
│ ╰───────────────────────────────────────╯                                                                       │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭────────────────────────────────────────── COUPLING MODEL (J1J2Square) ──────────────────────────────────────────╮
│ params= {'J2': 0.5, 'J1': 1.0, 'fields':       kwargs_lattice= {'bc': 'periodic', 'order':    S_operators= True │
│ [0.0, 0.0, 0.0]}                               'default_2'}                                                     │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭────────────────────────────────────────── NEURAL NETWORK (OnlyAnsatz) ──────────────────────────────────────────╮
│ name= OnlyAnsatz  setup= {'stage_0': {'template': {'Transversal': {'Factori...                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

────────────────────────────────────────────────────────  ─────────────────────────────────────────────────────────

********************* ARCHITECTURE INFO *********************

└── Trans_0   --->  (0)
    └── phi   --->  (00)


NN stats: 16 parameters (0.0001220703125 MB)

*************************************************************
Total samples: 2048

Initializing sampler...
Initializing Variational State...
Adding BestIterKeeper

Period 1 / 1:
Training ('Trans_0',) for 2000 epochs
LR: 0.05    ()
Diagonal shift: 1.0000e-02

Trans_0
   phi: train_0
None

Training ('Trans_0',) for 2000 epochs...


100%|██████████| 2000/2000 [03:43<00:00,  8.95it/s, Energy=-3.001+0.000j ± 0.066 [σ²=6.9e+00, R̂=1.012]]


VS phase: 10.776274533741006 ± 4.167340875412502  (complex)


In [21]:
import orbax.checkpoint as ocp
file = '/home/ihuarte/Escritorio/Ivan/NNs/new_pruebas/J1J2Square/FactorMod_Transversal_FactorMod/Size_4x4/ST_2000-A/UUID_d928c229/J1J2Square_FactorMod_simulation_4x4_J1J2_1.0_0.5_XYZ_0.0_0.0_0.0_date_20260129T214455_UUID_d928c229_vstate_parameters.orbax'
checkpointer = ocp.PyTreeCheckpointer()
a = checkpointer.restore(file)


In [22]:
a = a['Trans_0']
b = a['phi']
c = a['mod']

In [24]:
b.reshape((4,4)), c.reshape((4,4))

(Array([[0.0805346 , 0.07656922, 0.08204793, 0.06495796],
        [0.33201677, 0.3297288 , 0.32573277, 0.32163632],
        [0.05364157, 0.07194567, 0.05909465, 0.08406611],
        [0.3231367 , 0.3191219 , 0.32654166, 0.31885067]], dtype=float32),
 Array([[-0.5555412 ,  0.5554809 , -0.5551381 ,  0.5586005 ],
        [ 1.2212114 , -1.2233791 ,  1.2244273 , -1.2275373 ],
        [ 0.5616759 , -0.5578408 ,  0.5601896 , -0.55460143],
        [-1.2267637 ,  1.2278324 , -1.2250128 ,  1.2279726 ]],      dtype=float32))

In [26]:
(b*c).reshape(4,4)

Array([[-0.04474029,  0.04253274, -0.04554793,  0.03628555],
       [ 0.40546268, -0.40338334,  0.3988361 , -0.39482057],
       [ 0.03012918, -0.04013423,  0.03310421, -0.04662319],
       [-0.39641237,  0.3918282 , -0.4000177 ,  0.3915399 ]],      dtype=float32)

In [ ]:
from NN_module.schedule.schedule import Schedule
import optax

setup = {
    "print_arch": True,
    "learning_rate": {
        "epochs_struct": [[[50], [100], [200]]],
        "modes_struct": [[[["A"]], [["1", "110"]], [["10000"]]]],
        "lr_struct": [
            [[[0.01, 0.05]], [["lin(0.001, 0.1)", 0.3]], [["exp(0.1, 0.001)"]]]
        ],
        "repeat": [],
        "rescale": 1.0,
    },
    "architecture": {},
    "sampler": {},
}


sch = Schedule(setup, vstate.parameters)
sch.total_epochs
opt = optax.sgd
for period, info in sch.schedule():
    print(f"{info}")
    print(f"{period} {type(period)}\n")
    sch.transform_optimizer(vstate.parameters, opt, info, period)
    print("\n")

In [ ]:
import flax.linen as nn

arch_name = type(model).__name__
subarch_names = [
    name
    for name in model.__dict__.keys()
    if isinstance(model.__dict__[name], nn.Module)
]
arch_name, subarch_names

In [ ]:
model.__dict__["Trans"][0].__class__.__name__

In [ ]:
def is_subsequence(a, b):
    n, m = len(a), len(b)
    for i in range(m - n + 1):
        if b[i : i + n] == a:
            return True
    return False


a = (1, 2, 3)
b = (1, 2, 4, 3, 4, 5, 6)
is_subsequence(a, b)

In [ ]:
factory.setup